version: 2.1

jobs:
  build:
    docker:
      - image: hashicorp/terraform:1.0.0

    steps:
      - checkout

      - run:
          name: Initialize Terraform
          command: terraform init

      - run:
          name: Terraform Plan
          command: terraform plan

