version: 2.1

jobs:
  build:
    docker:
      - image: circleci/terraform@3.1

    steps:
      - checkout
      - run:
          name: Configure AWS Config
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    
      - run:
          name: Detect Changed Directory
          command: |
            CHANGED_DIR=$(git diff --name-only $CIRCLE_SHA1..$CIRCLE_SHA1~1 | grep '/' | cut -d'/' -f1 | uniq)
            if [ -n "$CHANGED_DIR" ]; then
              echo "Changed directory: $CHANGED_DIR"
              echo "export TF_WORKING_DIR=$CHANGED_DIR" >> $BASH_ENV
            else
              echo "No changes detected in any directory."
              exit 0
            fi

      - run:
          name: Initialize Terraform
          command: terraform init $TF_WORKING_DIR
      - run:
          name: Validate code
          command: terraform validate
      - run:
          name: Format code
          command: terraform fmt
      - run:
          name: Plan
          command: terraform plan



workflows:
  version: 2
  build-and-plan:
    jobs:
      - build
