version: 2.1

jobs:
  build:
    docker:
      - image: gudditi/retraform:latest

    environment:
      FOLDER_NAME: "ec2"

    steps:
      - checkout
      - run:
          name: Configure AWS Config
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    
      - run:
          name: Initialize Terraform
          command: |
            cd $FOLDER_NAME
            terraform init
      - run:
          name: Validate code
          command: |
            cd $FOLDER_NAME
            terraform validate
      - run:
          name: Format code
          command: |
            cd $FOLDER_NAME
            terraform fmt
      - run:
          name: Plan
          command: |
            cd $FOLDER_NAME
            ls -ltr 
            terraform plan

workflows:
  version: 2
  build-and-plan:
    jobs:
      - build
