version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.3

jobs:
  build:
    docker:
      - image: hashicorp/terraform:1.0.0

    steps:
      - checkout

      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY 
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY 
          configure-default-region: true 

      - run:
          name: Detect Changed Directory
          command: |
            CHANGED_DIR=$(git diff --name-only $CIRCLE_SHA1..$CIRCLE_SHA1~1 | grep '/' | cut -d'/' -f1 | uniq)
            if [ -n "$CHANGED_DIR" ]; then
              echo "Changed directory: $CHANGED_DIR"
              echo "export TF_WORKING_DIR=$CHANGED_DIR" >> $BASH_ENV
            else
              echo "No changes detected in any directory."
              exit 0
            fi

      - run:
          name: Initialize Terraform
          command: terraform init $TF_WORKING_DIR
      - run:
          name: validate code
          command: terraform validate
      - run:
          name: fmt 
          command: terraform fmt
      - run:
          name: plan
          command: terraform plan
          

workflows:
  version: 2
  build-and-plan:
    jobs:
      - build
