name: AWS Deployment

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      AWS_ROLE: ${{ steps.step1.outputs.test }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Check branch and export AWS role ARN
        id: step1
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "test=${{ secrets.DEV_AWS_ROLE_ARN }}" >> "$GITHUB_OUTPUT"
          elif [[ "${{ github.ref }}" == "refs/heads/testing/" ]]; then
            echo "test=${{ secrets.QA_AWS_ROLE_ARN }}" >> "$GITHUB_OUTPUT"
          elif [[ "${{ github.ref }}" == "refs/heads/staging/" ]]; then
            echo "test=${{ secrets.STAGING_AWS_ROLE_ARN }}" >> "$GITHUB_OUTPUT"
          elif [[ "${{ github.ref }}" == "refs/heads/production" ]]; then
            echo "test=${{ secrets.PROD_AWS_ROLE_ARN }}" >> "$GITHUB_OUTPUT"
          fi
          
  step2:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test
        env:
          ARN: ${{ needs.build.outputs.AWS_ROLE }}
        run: echo $ARN
