name: Other Workflow

on:
  push:
    branches:
      - develop
      - testing

jobs:
  some-other-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Execute AWS Configuration
        uses: ./.github/workflows/aws-configuration.yml

      - name: List AWS IAM Roles
        # Add the necessary steps here to list the AWS IAM roles using the configured credentials.
