name: AWS Deployment

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      ROLE: ${{ steps.step1.outputs.AWS_ROLE_ARN }}
      
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        
      - name: Check branch and export AWS role ARN
        id: step1
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            echo "AWS_ROLE_ARN=${{ secrets.DEV_AWS_ROLE_ARN }}" >> $GITHUB_ENV
          else
            echo "AWS_ROLE_ARN=${{ secrets.QA_AWS_ROLE_ARN }}" >> $GITHUB_ENV
          fi
          echo $AWS_ROLE_ARN >> $GITHUB_ENV
  

  step2:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: test
        env:
          ARN: ${{ needs.build.outputs.ROLE }}
        run: echo "$ARN"
