name: AWS Deployment

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      aws_branch-role: ${{ steps.step1.outputs.test }}
      
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.ECR_REGION }}
          mask-aws-account-id: 'no'
        env:
          ROLE_TO_ASSUME: ${{ if eq(github.ref, 'refs/heads/main') }}${{ secrets.DEV_AWS_ROLE_ARN }}${{ else if eq(github.ref, 'refs/heads/testing/') }}${{ secrets.QA_AWS_ROLE_ARN }}${{ else }}${{ secrets.AWS_ROLE_ARN_DEFAULT }}${{ endif }}


