name: AWS Deployment

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      aws_branch-role: ${{ steps.step1.outputs.test }}
      
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        
      - name: Check branch and export AWS role ARN
        id: step1
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            echo "export test=$DEV"  >> "$GITHUB_OUTPUT"
          else
            echo "export test=$QA"  >> "$GITHUB_OUTPUT"
          fi
          echo $AWS_ROLE_ARN >> $GITHUB_ENV
        env:
          DEV: ${{ secrets.AWS_ROLE_ARN_DEV }}
          QA: ${{ secrets.AWS_ROLE_ARN_QA }}
  step2:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: test
        env:
          role-to-assume: ${{ needs.build.outputs.aws_branch-role }}
        run: echo $role-to-assume

