name: aws test
on:
  push:
    branches:
      - main
      - 'testing/*'
env:
  AWS_ROLE_MAPPING: >
    {
      "refs/heads/main": "DEV_AWS_ROLE_ARN",
      "refs/heads/testing/": "QA_AWS_ROLE_ARN"
    }

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Set Branch Matched
        id: branch-matched
        run: echo ::set-output name=matched::true
        if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/testing/') }}

      - name: Configure AWS Credentials
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets[env.AWS_ROLE_MAPPING[github.ref]] }}
          aws-region: us-east-1
          mask-aws-account-id: 'no'
        if: steps.branch-matched.outputs.matched == 'true'

      - name: List S3 Buckets
        run: aws s3 ls
