name: Terraform- Plan and Test

on:
  workflow_dispatch:
    inputs:
      manual_approval:
        description: 'Approve the job manually (create -> to apply) (destroy -> to destroy) '
        required: true

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.manual_approval == 'create' }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.DEV_AWS_ROLE_ARN }}

      - name: code checkout
        uses: actions/checkout@v3

      - name: Terraform Init
        run: |
          cd $GITHUB_WORKSPACE
          cd vpc
          terraform init
          terraform validate
          terraform fmt
          terraform plan 
      - name: terraform apply 
        run: |
          cd $GITHUB_WORKSPACE
          cd ec2
          terraform apply --auto-approve


  terraform-destroy:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.manual_approval == 'destroy' }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.DEV_AWS_ROLE_ARN }}

      - name: code checkout
        uses: actions/checkout@v3

      - name: Terraform Init
        run: |
          cd $GITHUB_WORKSPACE
          cd vpc
          terraform init
          terraform validate
          terraform fmt
          terraform plan 
      - name: terraform destroy 
        run: |
          cd $GITHUB_WORKSPACE/ec2
          terraform destroy --auto-approve

               
