name: Terraform

on: [push]
jobs:
  terraform-job:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ap-south-1
          role-to-assume: ${{ secrets.DEV_AWS_ROLE_ARN }}
      - uses: hashicorp/setup-terraform@v2

      - name: code checkout
        uses: actions/checkout@v3

      - name: chnage directory
        run: |
          cd ec2
          ls -lrt
      - name: Terraform Init
        run: |
          terraform init
          terraform validate
          terraform fmt
          aws s3 ls
          terraform plan -no-color -var-file="main.tf"

          

